linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - gosec
    - gosimple
    - ineffassign
    - misspell
    - unconvert
    - unparam
    - unused
    - revive
    - predeclared

linters-settings:
  govet:
    # Shadow linter is now enabled separately
  golint:
    min-confidence: 0.8
  gofmt:
    simplify: true
  gosec:
    excludes:
      - G306 # Use of unsafe file permissions
      - G204 # Audit use of command execution (expected behavior for orchestration platform)
  unparam:
    # Allow unused function parameters (we often use cobra RunE signatures and similar)
    check-exported: false
  revive:
    rules:
      - name: unused-parameter
        disabled: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
    - linters:
        - unparam
      text: "parameter '.*' seems to be unused"
    - linters:
        - revive
      text: "unused-parameter"
    - linters:
        - errcheck
      # Make errcheck optional by excluding its diagnostics from failing the run
      text: ".*"
    - linters:
        - govet
      text: "copylocks: assignment copies lock value"
    - linters:
        - unparam
      text: "result .* is never used"
    - linters:
        - unparam
      text: ".* always receives .*"
    - linters:
        - unparam
      text: ".* is unused"
    - linters:
        - unparam
      text: "result .* is always nil"
    - linters:
        - unparam
      text: "result .* is always \"\""
    - linters:
        - staticcheck
      text: "SA1019: .* is deprecated"
    - linters:
        - predeclared
      text: "param .* has same name as predeclared identifier"
    - linters:
        - predeclared
      text: "function .* has same name as predeclared identifier"
    - linters:
        - predeclared
      text: "variable .* has same name as predeclared identifier"
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-files:
    - ".*\\.generated\\.go$"

  exclude-dirs:
    - vendor/
    - examples/

run:
  deadline: 5m
  tests: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true 