linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - gosec
    - gosimple
    - ineffassign
    - misspell
    - unconvert
    - unparam
    - unused
    - revive

linters-settings:
  govet:
    # Disable shadow checks to avoid failing on variable shadowing
    check-shadowing: false
  golint:
    min-confidence: 0.8
  gofmt:
    simplify: true
  gosec:
    excludes:
      - G204 # Audit use of command execution
  unparam:
    # Allow unused function parameters (we often use cobra RunE signatures and similar)
    check-exported: false
  errcheck:
    # Be lenient: don't require checking type assertions or blank-assignments
    check-type-assertions: false
    check-blank: false
  revive:
    rules:
      - name: unused-parameter
        disabled: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
    - linters:
        - unparam
      text: "parameter '.*' seems to be unused"
    - linters:
        - revive
      text: "unused-parameter"
    - linters:
        - errcheck
      # Make errcheck optional by excluding its diagnostics from failing the run
      text: ".*"
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - vendor/
    - examples/
  skip-files:
    - ".*\\.generated\\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true 