before:
  hooks:
    - go mod tidy

builds:
  - id: rune
    main: ./cmd/rune
    binary: rune
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/rzbill/rune/pkg/version.Version={{.Version}}
      - -X github.com/rzbill/rune/pkg/version.BuildTime={{.Date}}
      - -X github.com/rzbill/rune/pkg/version.Commit={{.Commit}}

  - id: runed
    main: ./cmd/runed
    binary: runed
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/rzbill/rune/pkg/version.Version={{.Version}}
      - -X github.com/rzbill/rune/pkg/version.BuildTime={{.Date}}
      - -X github.com/rzbill/rune/pkg/version.Commit={{.Commit}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - docs/**/*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:' 