# Rune Server Configuration Example

# Server endpoints
server:
  # gRPC endpoint for API services
  grpc_address: ":8080"
  
  # HTTP endpoint for REST gateway
  http_address: ":8081"
  
  # TLS configuration (for future use)
  tls:
    enabled: false
    cert_file: "/path/to/cert.pem"
    key_file: "/path/to/key.pem"

# Data directory for persistent storage
# If not specified, a default OS-specific path will be used
data_dir: "/var/lib/rune"

# Client configuration
client:
  timeout: 30s
  retries: 3

# Docker runner configuration
docker:
  # API version to use (if not specified, auto-negotiation is used)
  # api_version: "1.43"
  
  # Fallback API version to use if auto-negotiation fails
  fallback_api_version: "1.43"
  
  # Timeout for API version negotiation in seconds
  negotiation_timeout_seconds: 3

# Default namespace
namespace: "default"

# Authentication
auth:
  # Comma-separated list of API keys
  # Leave empty to disable authentication
  api_keys: ""
  provider: "token"  # Options: token, oidc, none
  token: ""  # Static token for simple auth

# Resources
resources:
  cpu:
    default_request: "100m"
    default_limit: "500m"
  memory:
    default_request: "128Mi"
    default_limit: "256Mi"

# Logging configuration
log:
  # Log level (debug, info, warn, error)
  level: "info"
  
  # Log format (future use)
  format: "json"

# Additional plugins/extensions (future use)
plugins:
  dir: "/usr/local/lib/rune/plugins"
  enabled:
    - "metrics"
    - "backup" 