app:
  name: webapp
  image: rune-hello-world
  tag: latest
  env:
    LOG_LEVEL: info
    FEATURE_FLAGS: beta-search,new-dashboard
svc:
  expose:
    portName: {{ values:portName }}
    host: api.example.local
    hostPort: 8080

