service:
  skip: true
  name: hello-world
  namespace: default
  image: nginx:alpine
  scale: 1
  ports:
    - name: http
      port: 80
  env:
    NAME: "World"
  resources:
    cpu:
      request: "100m"
      limit: "500m"
    memory:
      request: "50Mi"
      limit: "100Mi"
  health:
    liveness:
      type: http
      path: /
      port: 80
      initialDelaySeconds: 5
      intervalSeconds: 10
  networkPolicy:
    ingress:
      - from:
          - namespace: default
            service: hello-world
        ports:
          - http
    egress:
      - to:
          - cidr: 0.0.0.0/0
        ports:
          - http
  expose:
    port: http
    host: hello.local
  discovery:
    mode: load-balanced
  affinity:
    required:
      - region=us-east-1
    preferred:
      - zone=us-east-1a
  autoscale:
    enabled: true
    min: 1
    max: 5
    metric: cpu
    target: 50%
  secretMounts:
    - name: db-secret
      mountPath: /etc/secrets/db
      secretName: db-credentials
  configMounts:
    - name: app-config
      mountPath: /etc/config
      configName: app-settings 


service:
  skip: true
  name: hello-world-2
  namespace: default
  image: nginx:alpine
  scale: 1
  ports:
    - name: http
      port: 80

secrets:
  - name: db-credentials
    namespace: default
    data:
      - key: username
        value: admin-from-secret
      - key: password
        value: password-from-secret
  

secrets:  
  - name: keypairs-secret
    namespace: default
    data:
      sandbox-private.pem: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2d0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktrd2dnU2xBZ0VBQW9JQkFRRGRCdWxaZEZyZ3M3L0gKb3ZPaDZWMnJzUE1kMlllRjRZbGh2bTBLNnlSdWU2aUVrd2tPOWY2WEZhK1JxdDh5Z0Z1VjdjVWNYMnJlMjlXVgpVS24zZThKaTc3cHdrU1I1RGMyNjhkVCt1SFAxS0N1NHYyZW9wWU42QzVtNURweFd2dFJWNGtpUElnb2xYVjRUCjA1VnlPR25JYk5zcVI3YWFNZjdHRUtLV0YzVWppN2ZMdDV0VmliS0IzSytoZ1k4ZnlZSFVJZVM5eURtNjRqYzAKQ0lxQVlwblFQQTQvN21RWTNqK3VlSEo5dDhUU3NNQWdvU3kzdEZ6Wlh4VGNlNml4SHI2Nnd0RlJ3RmhONGtlbAo4bkpoVnhNMVNVMjFaRURpaThrcU56ajJWdGhqdzlHeVpHM3NVSG4yVGVJVzlHVktpOW5SbDBNNjJzcXNpbDVvCmdaQ2Z0cVpIQWdNQkFBRUNnZ0VCQUpmNk02T3R6UHNxdlpqQTVETVZxckh1cHd5RVVacHVIUy9YWjFVVm9HUlQKcE9rYnpTTzdaQVp4QTlydW1qQTRjRUVrVDkrVmdIK2l1emJEVTB0M2pvN0c5ZlNHNklSUVNJRGQzaTRUbUxBZQpvZ21UbXV3c2VyNEZrZnJjSUFYSmkybE9nY1BoalFacUw5RUVNSU5zWk5oS2VWeVdHT25ucko1Mk84Vm1kY1lzCithZGs2SFBybFZabDBxZVZlamtHajlpWnNwSU4xS0ljaW41SVExVW03SXJxRkt6cFp4ZTkrWmZDNmZkVFdiSEQKbklXd3YvZFhlb1VJU0FGTDY1Ri91NGV2cWVoNHRSZzMxMTRyK0U0SEY4T1E1RERxYlV4SzJWdDlhSVpXUUZFMwpsUE5xUmp6OUVzei81bmFBM0F3MGZuallCdkJmQk9udDM0d0p6bmVOaVpFQ2dZRUE5dUhlWVFzcVVIdkxVck96CkNQVFlOK05INUtGS2hkK2tHZ1pqZ1ZVZjlsNzhxSHEvN0pBQkdQK1E5aVR1bGNMTGhWdERYWHA0T1lyTkgzWVAKT1pIUDJJYWNRWHNUbWpkTUUvOTRsMjA0d0hQUFcwQ2wranJqL2dWRE11YXVnL1h4a2xIa1BETjNFQkx5K2NQVQp3bFRDa2g0Z1FaQ3pUOXNsZDgybjFEN2JPMGtDZ1lFQTVUQ1lnWE50c29pMkhaS2szZXlKNXZkMkNhZ2I3Z1NtClpUM3gxVGhiN1JBQ1c3UWpaUTgwek9SUVFzSUFMTmlMV1pETEpCNFc2VnBRVTVlbnJQWnJ1V0QxODlFTUVqTloKZzhIUkFQbmg0UmxtODVDZHVSZmdOUXZpYzlSanZYcHFudVA2b3l5dWlQMmw3dG1NdXVrYWMzemVSU1Z2dW5Cawp0SGNudTNOSHhROENnWUVBcWxBWlZFTWFsdGsvNDdhNkxOU1VFTUlIUjY4Sk5SK2FHcVlMb1I0elpZZ1RycnEzCmloK3gwaWdFUGZvdWFUd3ZvTGpiMlRIeW5HZW5xQ3VPeHoxUzhHRzBpK3UzRXkxUW0zOGpGdnV2S2Z6NnNFNEIKOG9VTDRhS0p3Q1NwZ2JsNlJHR2dIUE80RUd1eUdTSEN0YWs1YlFuQllObk5DYXI1eHhNbDAyTGxaSmtDZ1lBWgpiemd0ZllyWitsUURtaWVUdlZGY2dXL25DSEg1Q3lrUUtUeXlSZXZsdGhZYzZUUFlYa1NrekYyZjJ2bThBRmdPCm00UC93UnNYMEg4RGw5dnkxUElGZzU0bjdiWWlPdktmTFo0dE5vMzd0aDczdnIvU0w3VWhEZTJXbnlabWU3UmoKWjdlRDdreDhSWEhwdk5qaVVVWXZOTmRSNHlLd0ZSTUgrQVUveHo1YXZ3S0JnUURuOFpHNlRwaXhjbUZlM2puUQpLSW1GdUxVbHRHUlVUamxaYmxvRVNSNzEzSmhpcXZianU1ZVY1aUNJSXdnN21zZmpkbHF4eXNBcWtYRWREbmRvCk9XaUJ2c01LZzBxQk1obThGM25QcnVPSzJzUC92OGpQRTBxQzBHbnhENTFvOVQzWTBnMGR4VDBGNklVZWZZaW0KekhZUVhxWGd5U3lTMkdtU3Zoazd3elNxVVE9PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
      sandbox-public.pem: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEzUWJwV1hSYTRMTy94Nkx6b2VsZApxN0R6SGRtSGhlR0pZYjV0Q3Vza2JudW9oSk1KRHZYK2x4V3ZrYXJmTW9CYmxlM0ZIRjlxM3R2VmxWQ3A5M3ZDCll1KzZjSkVrZVEzTnV2SFUvcmh6OVNncnVMOW5xS1dEZWd1WnVRNmNWcjdVVmVKSWp5SUtKVjFlRTlPVmNqaHAKeUd6YktrZTJtakgreGhDaWxoZDFJNHUzeTdlYlZZbXlnZHl2b1lHUEg4bUIxQ0hrdmNnNXV1STNOQWlLZ0dLWgowRHdPUCs1a0dONC9ybmh5ZmJmRTByREFJS0VzdDdSYzJWOFUzSHVvc1I2K3VzTFJVY0JZVGVKSHBmSnlZVmNUCk5VbE50V1JBNG92SktqYzQ5bGJZWThQUnNtUnQ3RkI1OWszaUZ2UmxTb3ZaMFpkRE90cktySXBlYUlHUW43YW0KUndJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
      sandbox-pavilion-public.pem: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFqc1UwNVp6aHl6S1hLNWxwR2twcgpscFlpNGI2WUU0MzRQcHM4ODdoZXJYSTZYMXZ1NWlWcm82SlRlYVZ0ZGpSYzIzSEw2OHZSa1ZlU29vVVlKZXpkClVwK254QTI3UkdpRldzZDBJZUtrOWVZNkQvR3MzZndNTFBGcEh4c0F1SnZjZU5QeDJUc2VReEltcUlKa2FvNkkKcStTdmNLZ0tLT1F3WWxIUDFKaVBKUEIyVlA4TjVXd09KclpsRVU4eDgvVmRlb09sSkxyVjhWOCtGV091Q1EvNQpGS2d4Skk3eTNqN2JFRzFvUXJVZ3VpTC9mY3RKT2pmamhDSWQwVXo5ZTVLRThRWlBTZU5JOFk5ak1DTzA5RVo1CktocmVQdlVMMkNwZ1Jma0dNeXMxbUJxSTBBbTV3VHFDR09yaHJ0N1lCSm1JNkZTMkZIOGJvOW1DODVHTEV0MWgKT1FJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==

        
configMaps:
  - name: app-settings
    namespace: default
    data:
      - key: log-level
        value: "info-from-configmap"
      - key: name
        value: World-from-configmap
      - key: port
        value: "8099"