name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          check-latest: true
      - name: Build linux amd64
        run: |
          GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o dist/linux_amd64/rune ./cmd/rune
          GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o dist/linux_amd64/runed ./cmd/runed
      - name: Build linux arm64
        run: |
          GOOS=linux GOARCH=arm64 go build -ldflags "-s -w" -o dist/linux_arm64/rune ./cmd/rune
          GOOS=linux GOARCH=arm64 go build -ldflags "-s -w" -o dist/linux_arm64/runed ./cmd/runed
      - name: Archive artifacts
        run: |
          cd dist/linux_amd64 && tar -czf ../rune_linux_amd64.tar.gz rune runed && cd -
          cd dist/linux_arm64 && tar -czf ../rune_linux_arm64.tar.gz rune runed && cd -
          sha256sum dist/*.tar.gz > dist/checksums.txt
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/rune_linux_amd64.tar.gz
            dist/rune_linux_arm64.tar.gz
            dist/checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}