name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          check-latest: true
      - name: Build all platforms
        run: |
          # Build for all target platforms using Makefile
          make build GOOS=linux GOARCH=amd64
          make build GOOS=linux GOARCH=arm64
          make build GOOS=darwin GOARCH=amd64
          make build GOOS=darwin GOARCH=arm64
          
          # Create dist directories and copy binaries
          mkdir -p dist/linux_amd64 dist/linux_arm64 dist/darwin_amd64 dist/darwin_arm64
          
          # Copy Linux binaries
          cp bin/rune dist/linux_amd64/
          cp bin/runed dist/linux_amd64/
          cp bin/rune dist/linux_arm64/
          cp bin/runed dist/linux_arm64/
          
          # Copy macOS binaries (CLI only for now)
          cp bin/rune dist/darwin_amd64/
          cp bin/rune dist/darwin_arm64/
          
          # List built binaries
          echo "Built binaries:"
          find dist -type f -executable
      - name: Archive artifacts
        run: |
          # Full server packages (rune + runed)
          cd dist/linux_amd64 && tar -czf ../rune_linux_amd64.tar.gz rune runed && cd -
          cd dist/linux_arm64 && tar -czf ../rune_linux_arm64.tar.gz rune runed && cd -
          
          # CLI-only packages (just rune binary)
          cd dist/linux_amd64 && tar -czf ../rune-cli_linux_amd64.tar.gz rune && cd -
          cd dist/linux_arm64 && tar -czf ../rune-cli_linux_arm64.tar.gz rune && cd -
          cd dist/darwin_amd64 && tar -czf ../rune-cli_darwin_amd64.tar.gz rune && cd -
          cd dist/darwin_arm64 && tar -czf ../rune-cli_darwin_arm64.tar.gz rune && cd -
          
          sha256sum dist/*.tar.gz > dist/checksums.txt
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/rune_linux_amd64.tar.gz
            dist/rune_linux_arm64.tar.gz
            dist/rune-cli_linux_amd64.tar.gz
            dist/rune-cli_linux_arm64.tar.gz
            dist/rune-cli_darwin_amd64.tar.gz
            dist/rune-cli_darwin_arm64.tar.gz
            dist/checksums.txt
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}